name: docker

on: push

jobs:
   buildx:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix: 
        version: ["15-jre", "14-jre", "8-jre", "14-jdk-slim", "15-jdk", "14-jdk", "8-jdk"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
        if: github.ref == 'refs/heads/master'
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.0
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Install yq (mikefarah, go)
        run: sudo su -c 'wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq'
      -
        name: Run Buildx (${{ matrix.version }})
        run: |
          docker buildx build \
            --platform $(yq r platform-matrix.yml ${{ matrix.version }}) \
            --output "type=image,push=$([[ $GITHUB_REF == "refs/heads/master" ]] && echo true || echo false)" \
            -f ${{ matrix.version }}.Dockerfile -t jcxldn/openjdk-alpine:${{ matrix.version }} .